### ISSUE TITLE
how to get DC values?

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/ispyb-api#103]
Hello,
I'm just trying to understand the best way to use the python API to interact with our ISPyB database. I was wondering if this is a legit way to grab the filePrefix for a specific DC:
  
```
with ispyb.open(sys.argv[1]) as conn:
    core = conn.core
    mxacquisition = conn.mx_acquisition
    dc = mxacquisition.get_data_collection(1089771)
    fp = dc.imgprefix
    print("filePrefix is: {}".format(fp))
```

This doesn't work for imagePrefix (the actual column name in ispyb.DataCollection) or imgprefix (a string I found buried in the ispyb-api code).

I get:

`AttributeError: 'DataCollection' object has no attribute 'imgprefix'`
or
`AttributeError: 'DataCollection' object has no attribute 'imagePrefix'`

How can I see a list of attributes that get_data_collection supports? or how can I extend it to allow more attributes?

**Comment by graeme-winter** [comment]
Looking through `ispyb-api/ispyb/model/datacollection.py` looks like the emphasis is on `file_template` - you can grab the prefix with `prefix = file_template.split("#")[0]`?

**Comment by Anthchirp** [comment]
The list of attributes can be found on https://ispyb.readthedocs.io/en/latest/api.html#module-ispyb.model.datacollection, and you are welcome to extend this list following a similar format as the existing definitions:
https://github.com/DiamondLightSource/ispyb-api/blob/c9dcdac43ffb4ea5fe367a760b16ab152a6bb9d5/ispyb/model/datacollection.py#L157-L162

**Comment by Anthchirp** [comment]
I believe this can be closed. Feel free to reopen if you have more questions
