### ISSUE TITLE
Testing broken

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/ispyb-api#106]
Travis doesn't seem to run any more. Should probably look into setting up Azure for the repository.

**Comment by KarlLevik** [comment]
Travis does run, but for some reason it's not visible on the actual PRs. You can still find the results here:
https://travis-ci.org/github/DiamondLightSource/ispyb-api

**Comment by Anthchirp** [comment]
Indeed. I suspect it's a travis-ci.org deprecation thing. I'll see if I can migrate the repository to travis-ci.com
