### ISSUE TITLE
trouble parsing some autoPROC.xml files

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/ispyb-api#154]
I'm attempting to use the `xml_file_to_dict` and  `mx_data_reduction_to_ispyb` functions in `xmltools.py` to upsert some autoPROC (1.0.5) results to ISPyB. Sometimes this works... sometimes not. 

If autoPROC processed a directory with a single wedge of contiguous files then things go well.

If autoPROC processes a directory with a more than one wedge of contiguous files then things do not go well. The `autoPROC.xml` file will contain multiple instances of `AutoProcScalingContainer ` and `AutoProcIntegrationContainer`

```
Traceback (most recent call last):
  File "/home/classen/projects/ispyb/ispyb-populate/src/ispyb_populate/process.py", line 309, in upsert_ap_xml_results
    ) = mx_data_reduction_to_ispyb(mx_data_reduction_dict,
  File "/home/classen/projects/ispyb/ispyb-api/src/ispyb/xmltools.py", line 98, in mx_data_reduction_to_ispyb
    int_containers = xmldict["AutoProcScalingContainer"]["AutoProcIntegrationContainer"]
TypeError: list indices must be integers or slices, not str
```

I'm guessing that data is never organized this way at DLS. i.e. directory with multiple wedges.

I could provide examples of problematic autoPROC.xml files if that would help debug the issue. OR if there is an alternate way to process/upsert autoPROC results I'm all ears.

**Comment by graeme-winter** [comment]
We run autoPROC pointing at specific data rather than folders so don't stumble across this issue. We should be able to reproduce it in house by just running autoPROC on a directory and trying to upload.

For multi-sweep data we only use xia2 and multiplex {I think} so probably why we've never stumbled across this.
