### ISSUE TITLE
mx_data_reduction_to_ispyb does not upsert processingStatus from autoPROC.xml

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/ispyb-api#168]
After having run autoPROC on some data, I am left with an `autoPROC.xml` file which I am able to add to ispyb using the `mx_data_reduction_to_ispyb` function in `xmltools.py`.

Even though the xml file is indicative of the processing run being complete (i.e. `<processingStatus>1</processingStatus>`) This value remains as `NULL` in the ispyb database (table: ` ispyb.AutoProcProgram` column : `processingStatus`). Is there some other way (via python preferably ) that I should be indicating that a processing run is complete?

**Comment by KarlLevik** [comment]
Yes. You can use the [upsert_program_ex(...)](https://github.com/DiamondLightSource/ispyb-api/blob/master/src/ispyb/sp/mxprocessing.py#L237) method. Assuming you have the id of the `AutoProcProgram` row, just leave any params as None if you don't want to modify their values. Something like:
```python
mx_processing = conn.mx_processing
mx_processing.upsert_program_ex(
  program_id=id, 
  command=None,
  name=None,
  status=1,
  message=some_message,
  time_start=None,     # unsure if this is empty, if so you may want to put something here
  time_update=None, # same
  environment=None,
  job_id=None,
  time_defined=None,
)
```
This calls the [upsert_processing_program](https://github.com/DiamondLightSource/ispyb-database/blob/master/schemas/ispyb/stored_programs/sp_upsert_processing_program.sql) stored procedure.

**Comment by dsclassen** [comment]
This works. Thank you.
