### ISSUE TITLE
Cannot use Python 3.11 as pinned mysql-connector-python version is not available on conda-forge

### ISSUE THREAD

**Issue by PeterC-DLS** [DiamondLightSource/ispyb-api#202]
We may be able to get around it by building the connector package locally or trying to use 3.10.

**Comment by rjgildea** [comment]
It's possible that the [issue seen with mysql-connector-python 8.0.30](https://github.com/DiamondLightSource/ispyb-api/issues/183) is [fixed by 8.0.32](https://github.com/mysql/mysql-connector-python/blob/3fe87a163de1c1dfcf1de60bbabecc30394c3ef6/CHANGES.txt#L39).

**Comment by PeterC-DLS** [comment]
Python 3.10 works for us so no rush.

**Comment by rjgildea** [comment]
An upstream issue with the [mysql-connector-python-feedstock 8.0.32 build](https://github.com/conda-forge/mysql-connector-python-feedstock/pull/78) is blocking the [ispyb-feedstock 8.0.1 build](https://github.com/conda-forge/ispyb-feedstock/pull/68).

**Comment by rjgildea** [comment]
`ispyb=8.0.1` now available on conda-forge:
```
$ mamba search ispyb=8.0.1
...
Loading channels: done
# Name                       Version           Build  Channel             
ispyb                          8.0.1    pyhd8ed1ab_0  conda-forge
```
