### ISSUE TITLE
Make extended data collection information accessible via DCID model

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/ispyb-api#68]
Currently it is not possible to access eg. the resolution column of a data collection when given the DCID.

**Comment by KarlLevik** [comment]
Yes, I think that calls for a new stored procedure. The `retrieve_dc_main_v2` is meant to retrieve only a certain subset of the columns, as we also have `upsert_dc_main_v2` that upserts the same columns, and `update_dc_experiment_v2` which updates the "experiment" columns which includes resolution.

I will write a new stored procedure that retrieves all the columns (except deprecated ones and other undesirables).

**Comment by KarlLevik** [comment]
OK, I've made a PR for this: https://github.com/DiamondLightSource/ispyb-api/pull/71
