### ISSUE TITLE
retrieve_sessions_for_beamline_and_run gives unit test error.

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/ispyb-api#79]
There were a few other unit test errors, but this is the first one.

I only see ```retrieve_sessions_for_person_login```
no ```test_retrieve_sessions_for_beamline_and_run``` in the latest ispyb database.

```
__________________________________________________________________________ test_retrieve_sessions_for_beamline_and_run ___________________________________________________________________________

testdb = <ispyb.connector.mysqlsp.main.ISPyBMySQLSPConnector object at 0x7f6993fcb400>

    def test_retrieve_sessions_for_beamline_and_run(testdb):
>       rs = testdb.core.retrieve_sessions_for_beamline_and_run("i03", "2016-01")
E       AttributeError: 'Core' object has no attribute 'retrieve_sessions_for_beamline_and_run'

tests/test_core.py:100: AttributeError```

**Comment by Anthchirp** [comment]
The test runs without issues [on Travis](https://travis-ci.org/DiamondLightSource/ispyb-api/jobs/530178867).
Do you have a test configuration file set up correctly?

**Comment by KarlLevik** [comment]
> I only see retrieve_sessions_for_person_login
no test_retrieve_sessions_for_beamline_and_run in the latest ispyb database.

You'll probably have to update the stored procedures in your database. If you pull the latest changes into your `ispyb-database` source code folder, you can replace/install all the stored procedures with the latest using a command like this:

`mysql ispyb < ispyb-database/schema/routines.sql`

Or you can install just that particular stored procedure:

`mysql ispyb < ispyb-database/schema/stored_programs/sp_retrieve_sessions_for_beamline_and_run.sql`

**Comment by dsclassen** [comment]
That was it. Thanks. For some reason I thought I had already updated the schema, but it turns out I had only fetched from git, and not actually made the changes to the running MySQL server.

I can now run the ```retrieve_sessions_for_beamline_and_run``` from MySQL Workbench, but pytest still gives me an error on line 100 when trying to process the test_core.py file.

```__________________________________________________________________________ test_retrieve_sessions_for_beamline_and_run ___________________________________________________________________________

testdb = <ispyb.connector.mysqlsp.main.ISPyBMySQLSPConnector object at 0x7fb307191438>

    def test_retrieve_sessions_for_beamline_and_run(testdb):
>       rs = testdb.core.retrieve_sessions_for_beamline_and_run("i03", "2016-01")
E       AttributeError: 'Core' object has no attribute 'retrieve_sessions_for_beamline_and_run'

tests/test_core.py:100: AttributeError```

**Comment by dsclassen** [comment]
```pip install . ``` has fixed this error.
not exactly sure why... maybe I had the wrong version of mysql-connector installed?
closing for now.

**Comment by KarlLevik** [comment]
Glad to hear you made it work. It sounded like a problem in the ispyb-api code - it seems somehow you had the new test, but not the related source code in the `core.py` module. Strange.

**Comment by Anthchirp** [comment]
If you run `pip install` without the `-e` option as mentioned in https://github.com/DiamondLightSource/ispyb-api#installation then you install a copy into the python module directory. If you then update the source this copy will not be updated, and you may get into a situation where pytest runs the updated test file but an `import ispyb` will still point to and load the previously made copy.
